package psupickanumber;

public class PickANumberGUI extends javax.swing.JFrame {
    
//    private int secretNumber;
    private RandomNumberGenerator rng = new RandomNumberGenerator();
    private RadioButtonSelectionStrategy rdoStrategy = new RadioButtonSelectionStrategy();
    /**
     * Creates new form PickANumberGUI
     */
    public PickANumberGUI() {
        initComponents();
        this.rdoOne.setActionCommand(this.rdoOne.getText());
        this.rdoTwo.setActionCommand(this.rdoTwo.getText());
        this.rdoThree.setActionCommand(this.rdoThree.getText());
        this.rdoFour.setActionCommand(this.rdoFour.getText());
        this.rdoFive.setActionCommand(this.rdoFive.getText());
        this.rdoSix.setActionCommand(this.rdoSix.getText());
        this.rdoSeven.setActionCommand(this.rdoSeven.getText());
        this.rdoEight.setActionCommand(this.rdoEight.getText());
        this.rdoNine.setActionCommand(this.rdoNine.getText());
        this.rdoTen.setActionCommand(this.rdoTen.getText());
        this.rdoEleven.setActionCommand(this.rdoEleven.getText());
        this.rdoTwelve.setActionCommand(this.rdoTwelve.getText());
//        this.secretNumber = rng.getSecretNumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpChoices = new javax.swing.ButtonGroup();
        JPanel = new javax.swing.JPanel();
        lblInstructions = new javax.swing.JLabel();
        btnSelection = new javax.swing.JButton();
        rdoOne = new javax.swing.JRadioButton();
        rdoTwo = new javax.swing.JRadioButton();
        rdoThree = new javax.swing.JRadioButton();
        rdoFour = new javax.swing.JRadioButton();
        rdoFive = new javax.swing.JRadioButton();
        rdoSix = new javax.swing.JRadioButton();
        rdoSeven = new javax.swing.JRadioButton();
        rdoEight = new javax.swing.JRadioButton();
        lblResults = new javax.swing.JLabel();
        rdoNine = new javax.swing.JRadioButton();
        rdoTen = new javax.swing.JRadioButton();
        rdoEleven = new javax.swing.JRadioButton();
        rdoTwelve = new javax.swing.JRadioButton();
        btnExit = new javax.swing.JButton();
        txtResults = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pick-A-Number");
        setResizable(false);

        JPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pick a Number"));
        JPanel.setToolTipText("");

        lblInstructions.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions.setText("I'm think of a number between 1 and 12...");

        btnSelection.setText("Make Selection");
        btnSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectionActionPerformed(evt);
            }
        });

        btnGrpChoices.add(rdoOne);
        rdoOne.setSelected(true);
        rdoOne.setText("1");
        rdoOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoOneActionPerformed(evt);
            }
        });

        btnGrpChoices.add(rdoTwo);
        rdoTwo.setText("2");
        rdoTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTwoActionPerformed(evt);
            }
        });

        btnGrpChoices.add(rdoThree);
        rdoThree.setText("3");

        btnGrpChoices.add(rdoFour);
        rdoFour.setText("4");

        btnGrpChoices.add(rdoFive);
        rdoFive.setText("8");

        btnGrpChoices.add(rdoSix);
        rdoSix.setText("7");

        btnGrpChoices.add(rdoSeven);
        rdoSeven.setText("6");

        btnGrpChoices.add(rdoEight);
        rdoEight.setText("5");

        lblResults.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblResults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnGrpChoices.add(rdoNine);
        rdoNine.setText("12");

        btnGrpChoices.add(rdoTen);
        rdoTen.setText("11");

        btnGrpChoices.add(rdoEleven);
        rdoEleven.setText("10");

        btnGrpChoices.add(rdoTwelve);
        rdoTwelve.setText("9");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtResults.setBackground(new java.awt.Color(238, 238, 238));
        txtResults.setBorder(null);

        org.jdesktop.layout.GroupLayout JPanelLayout = new org.jdesktop.layout.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, JPanelLayout.createSequentialGroup()
                .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(JPanelLayout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnSelection)
                        .add(10, 10, 10))
                    .add(JPanelLayout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(lblResults, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                            .add(rdoThree)
                            .add(rdoOne)
                            .add(rdoTwo)
                            .add(rdoFour))
                        .add(55, 55, 55)
                        .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                            .add(rdoFive)
                            .add(rdoSix)
                            .add(rdoSeven)
                            .add(rdoEight))))
                .add(20, 20, 20)
                .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(rdoTen)
                        .add(rdoNine)
                        .add(rdoEleven)
                        .add(rdoTwelve))
                    .add(btnExit))
                .add(81, 81, 81))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, JPanelLayout.createSequentialGroup()
                .add(0, 34, Short.MAX_VALUE)
                .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(txtResults, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 334, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblInstructions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPanelLayout.createSequentialGroup()
                .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(JPanelLayout.createSequentialGroup()
                        .add(7, 7, 7)
                        .add(lblInstructions)
                        .add(18, 18, 18)
                        .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(rdoOne)
                            .add(JPanelLayout.createSequentialGroup()
                                .add(rdoEight)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rdoSeven))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, JPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(rdoTwo))
                    .add(JPanelLayout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(rdoTwelve)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rdoEleven)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(JPanelLayout.createSequentialGroup()
                        .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(JPanelLayout.createSequentialGroup()
                                .add(rdoSix)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rdoFive))
                            .add(JPanelLayout.createSequentialGroup()
                                .add(rdoTen)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rdoNine))
                            .add(JPanelLayout.createSequentialGroup()
                                .add(rdoThree)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rdoFour)))
                        .add(36, 36, 36))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, JPanelLayout.createSequentialGroup()
                        .add(lblResults, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(19, 19, 19)))
                .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnExit)
                    .add(btnSelection))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(txtResults, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .add(12, 12, 12))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(JPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(JPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoOneActionPerformed
        this.rdoOne.setActionCommand("1");
    }//GEN-LAST:event_rdoOneActionPerformed

    private void rdoTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoTwoActionPerformed

    private void btnSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectionActionPerformed
        String radioChoice = this.btnGrpChoices.getSelection().getActionCommand();
//        this.lblResults.setText(this.rdoStrategy.determineIfThereWasAMatch(rng, radioChoice));
        this.txtResults.setText(this.rdoStrategy.determineIfThereWasAMatch(rng, radioChoice));
//        this.txtResults.setText(this.rdoStrategy.getNumberOfGuesses());
    }//GEN-LAST:event_btnSelectionActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGrpChoices;
    private javax.swing.JButton btnSelection;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblResults;
    private javax.swing.JRadioButton rdoEight;
    private javax.swing.JRadioButton rdoEleven;
    private javax.swing.JRadioButton rdoFive;
    private javax.swing.JRadioButton rdoFour;
    private javax.swing.JRadioButton rdoNine;
    private javax.swing.JRadioButton rdoOne;
    private javax.swing.JRadioButton rdoSeven;
    private javax.swing.JRadioButton rdoSix;
    private javax.swing.JRadioButton rdoTen;
    private javax.swing.JRadioButton rdoThree;
    private javax.swing.JRadioButton rdoTwelve;
    private javax.swing.JRadioButton rdoTwo;
    private javax.swing.JTextField txtResults;
    // End of variables declaration//GEN-END:variables
}
