package psupickanumber;

public class PickANumberDropDownGUI extends javax.swing.JFrame {
    
//    private int secretNumber;
    private RandomNumberGenerator rng = new RandomNumberGenerator();
    private NumberComparisonSelectionStrategy ddlStrategy = new NumberComparisonSelectionStrategy();
    private Object currentSelection;
    private String selectionString;
    /**
     * Creates new form PickANumberGUI
     */
    public PickANumberDropDownGUI() {
        initComponents();
        currentSelection = this.ddlNumberChoice.getSelectedItem();
        selectionString = currentSelection.toString();
        System.out.println(selectionString);
//        this.ddlNumberChoice.setActionCommand(this.ddlNumberChoice.getSelectedIndex());
//        this.secretNumber = rng.getSecretNumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        lblInstructions = new javax.swing.JLabel();
        btnSelection = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtResults = new javax.swing.JTextField();
        ddlNumberChoice = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pick-A-Number");
        setResizable(false);

        JPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pick a Number"));
        JPanel.setToolTipText("");

        lblInstructions.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions.setText("I'm think of a number between 1 and 12...");

        btnSelection.setText("Make Selection");
        btnSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectionActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtResults.setBackground(new java.awt.Color(238, 238, 238));
        txtResults.setBorder(null);

        ddlNumberChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        org.jdesktop.layout.GroupLayout JPanelLayout = new org.jdesktop.layout.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, JPanelLayout.createSequentialGroup()
                .add(0, 34, Short.MAX_VALUE)
                .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(txtResults, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 334, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblInstructions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, JPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, JPanelLayout.createSequentialGroup()
                        .add(ddlNumberChoice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(43, 43, 43)
                        .add(btnSelection)
                        .add(63, 63, 63))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, JPanelLayout.createSequentialGroup()
                        .add(btnExit)
                        .add(97, 97, 97))))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JPanelLayout.createSequentialGroup()
                .add(7, 7, 7)
                .add(lblInstructions)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ddlNumberChoice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnSelection))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnExit)
                .add(18, 18, 18)
                .add(txtResults, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(JPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(JPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectionActionPerformed
        currentSelection = this.ddlNumberChoice.getSelectedItem();
        selectionString = currentSelection.toString();
        this.txtResults.setText(this.ddlStrategy.compareTheNumbers(rng, selectionString));
    }//GEN-LAST:event_btnSelectionActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSelection;
    private javax.swing.JComboBox ddlNumberChoice;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JTextField txtResults;
    // End of variables declaration//GEN-END:variables
}
